# Generated by Django 2.1.3 on 2018-11-08 13:11

import adminsortable.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Security Needs', max_length=255)),
                ('description', models.TextField(default='')),
                ('level', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Security Needs - (Confidentiality, Integrity, Availability)',
                'verbose_name_plural': 'Security Needs - (Confidentiality, Integrity, Availability)',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('rule_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rule_order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Section Title', max_length=255)),
                ('description', models.TextField(default='')),
                ('section_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['section_order'],
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='section',
            field=adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='securitypolicy.Section'),
        ),
    ]
