# Generated by Django 2.1.3 on 2018-11-12 15:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securitypolicy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='rule_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='section_order',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
