# Generated by Django 2.1.3 on 2018-11-12 20:42

import adminsortable.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securitypolicy', '0002_auto_20181112_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Section Title', max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('section', adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='securitypolicy.Section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='rule',
            name='section',
        ),
        migrations.AddField(
            model_name='rule',
            name='subsection',
            field=adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='securitypolicy.SubSection'),
        ),
    ]
