# Generated by Django 2.1.3 on 2018-11-13 13:40

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securitypolicy', '0004_auto_20181113_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='section',
            field=adminsortable.fields.SortableForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='securitypolicy.Section'),
        ),
    ]
