# Generated by Django 2.1.3 on 2018-11-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securitypolicy', '0005_rule_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleProxyModel',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Import / Export Rules',
                'proxy': True,
                'indexes': [],
            },
            bases=('securitypolicy.rule',),
        ),
        migrations.AlterField(
            model_name='rule',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='securitypolicy.Section'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='securitypolicy.SubSection'),
        ),
    ]
