# Generated by Django 2.1.3 on 2018-11-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('securitypolicy', '0006_auto_20181114_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='securitypolicy.Section'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='securitypolicy.SubSection'),
        ),
    ]
